### ISSUE TITLE
Use java system properties instead of dotenv external library

### ISSUE THREAD

**Issue by souenzzo** [bowbahdoe/caveman#12]
Replacing `start-env` with this code

```clojure
(defn start-env
  []
  (let [p (System/getProperties)
        dot-env (io/file ".env")]
    (when (.exists dot-env)
      (.load p (io/reader dot-env)))))
```

We are able to replace these [Dotenv/.get](https://github.com/search?q=repo%3Abowbahdoe%2Fcaveman+Dotenv%2F.get&type=code) calls with `(System/getProperty "POSTGRES_USERNAME")` and `(Long/getLong "PORT")`

PROS:
- One less library
- out-of-the-box parsing
- ~easy default values: `(Long/getLong "PORT" 8080)`~ (dotenv also support default values)
- it is possible to use long names `app.server.port=8080` (short names like `PORT` are also supported)
- Property reader supports both `port: 8080` and `PORT=8080` syntaxes
- Easy REPL overwrite: `(System/setProperty "PORT" "3030")`
- Easier to interact with java API's like `org.slf4j.simpleLogger.defaultLogLevel=info`

CONS:
- Bit more code

**Comment by bowbahdoe** [comment]
You missed some cons:

* If you print it out it is giant. It makes it really hard to visually inspect the system

<img width="804" alt="image" src="https://github.com/user-attachments/assets/50bbf77c-36b8-432a-9e97-50d8700304f3">

As compared to 

<img width="840" alt="image" src="https://github.com/user-attachments/assets/7751a8a6-b79d-46e3-8a55-ba6259d884c0">

* The fact that it actually mutates a global resource is less than ideal. 
* Supports divergent syntaxes

**Comment by bowbahdoe** [comment]
I guess to note another approach - instead of environment variables passing around a full (maybe nested) config file is possible.

The reason I don't want to recommend that is
* Now that you have nested maps you need to understand structure of those maps
* People will be tempted to go down a pointless rabbit hole of spec-ing that map or in other ways making orchestrations
